[package]
name = "dyndns"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.140"
tokio = { version = "1.45", features = ["rt-multi-thread", "macros"] }
